<?php


namespace App\Http\Resources;


use App\Models\Blog;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class BlogCommentResource extends JsonResource
{
    public function toArray(Request $request)
    {
        return [
            'id' => (string)$this->id,
            'name' => $this->name,
            'email' => $this->email,
            'message' => $this->message,
            'blog' => Blog::query()->find($this->blog_id)->first(['id','name']),
        ]; // TODO: Change the autogenerated stub
    }
}
